### ISSUE TITLE
Module not Found

### ISSUE THREAD

**Issue by khrome83** [yargalot/gulp-accessibility#6]
When I install the plugin and try to run it. I get module not found 100% of the time. I can verify the plugin is in the package, it is installed in the directory of the correct name, it is being called with the correct name, and it is being used the correct way. I am only assume it is a issue with the current version. 

Thanks.

**Comment by khrome83** [comment]
```
Error: Cannot find module 'gulp-accessibility'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kzx5cv/Documents/Code/opel-aem-workspace/opel/gulp-aem-workflow/tasks/wcag.js:6:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by khrome83** [comment]
As you can see the module is in the node_modules folder.

```
sc5-styleguide      gulp-mustache       gulp-shell
lodash          gulp-sass       gulp-sourcemaps
bower           tiny-lr         del
browser-sync        yargs           gulp-autoprefixer
gulp-accessibility  glob            gulp-concat
gulp-jshint     gulp-jscs       gulp-watch
gulp-uglify     gulp-livereload     jshint-stylish
gulp            gulp-minify-css     graceful-fs
gulp-connect        gulp-plumber        gulp-jscs-stylish
gulp-if         gulp-replace        gulp-rename
```

**Comment by khrome83** [comment]
latest update seems to have resolved this issue
